import { useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useMarketStats } from "@/hooks/useMarketStats";

/**
 * Cinematic hero for the AutoNex home page.
 *
 * Layout: full-bleed responsive <picture> background (mobile portrait /
 * tablet 4:3 / desktop 16:9 — sources generated by scripts/optimize-hero.mjs
 * into public/hero/) overlaid by a horizontal-then-vertical gradient that
 * keeps text readable on every aspect ratio. A solid navy gradient sits
 * underneath the picture as a fallback so the section stays usable while
 * the optimized images are still being generated.
 *
 * Copy intentionally short: H1 with the cyan-accented "véhicule" word
 * (matches the cyan "x" in the AutoNex logo for brand consistency), a
 * subtitle that names the actual anti-scam value-prop, a single unified
 * search bar, three text-link secondary CTAs, and a discrete real-data
 * stats line at the bottom (zeros until useMarketStats resolves — line
 * stays hidden while loading and when both counters are zero).
 */
export function HeroCinematic() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [searchQuery, setSearchQuery] = useState("");
  const { data: stats } = useMarketStats();

  const handleSearch = (e: FormEvent) => {
    e.preventDefault();
    const q = searchQuery.trim();
    navigate(q ? `/recherche?q=${encodeURIComponent(q)}` : "/recherche");
  };

  return (
    <section
      aria-label={t("hero.aria", "Recherche de véhicule sur AutoNex")}
      className="relative isolate overflow-hidden bg-gradient-to-br from-navbar via-slate-900 to-navbar"
    >
      <picture className="absolute inset-0 -z-10">
        <source
          media="(max-width: 768px)"
          type="image/webp"
          srcSet="/hero/hero-mobile-640.webp 640w, /hero/hero-mobile-1080.webp 1080w, /hero/hero-mobile-1440.webp 1440w"
          sizes="100vw"
        />
        <source
          media="(max-width: 1280px)"
          type="image/webp"
          srcSet="/hero/hero-tablet-1024.webp 1024w, /hero/hero-tablet-2048.webp 2048w"
          sizes="100vw"
        />
        <source
          type="image/webp"
          srcSet="/hero/hero-desktop-1280.webp 1280w, /hero/hero-desktop-1920.webp 1920w, /hero/hero-desktop-2560.webp 2560w"
          sizes="100vw"
        />
        <img
          src="/hero/hero-desktop-1920.jpg"
          alt=""
          aria-hidden="true"
          loading="eager"
          fetchPriority="high"
          decoding="async"
          className="h-full w-full object-cover object-center"
        />
      </picture>

      <div
        aria-hidden="true"
        className="absolute inset-0 -z-10 bg-gradient-to-r from-black/85 via-black/55 to-transparent md:from-black/75 md:via-black/40"
      />
      <div
        aria-hidden="true"
        className="absolute inset-0 -z-10 bg-gradient-to-b from-black/70 via-transparent to-transparent md:hidden"
      />

      <div className="container mx-auto px-4 py-20 md:py-28 lg:py-36 min-h-[640px] md:min-h-[720px] flex flex-col justify-center">
        <div className="max-w-2xl">
          <h1 className="font-serif text-4xl sm:text-5xl lg:text-6xl text-white leading-[1.05] tracking-tight">
            {t("hero.title.line1Prefix", "Trouvez le ")}
            <span className="text-sky-400">{t("hero.title.accent", "véhicule")}</span>
            <br />
            {t("hero.title.line2", "qui vous correspond")}
          </h1>

          <p className="mt-6 max-w-lg font-sans text-base sm:text-lg text-white/90 leading-relaxed">
            {t(
              "hero.subtitle",
              "Annonces vérifiées partout à Madagascar. Vendeurs identifiés, négociation simplifiée.",
            )}
          </p>

          <form
            onSubmit={handleSearch}
            className="mt-8 flex flex-col sm:flex-row gap-2 sm:gap-0 sm:bg-white/95 backdrop-blur sm:rounded-full sm:p-1.5 sm:shadow-2xl sm:max-w-xl"
          >
            <div className="relative flex-1">
              <Search
                aria-hidden="true"
                className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-foreground/60 hidden sm:block"
              />
              <Input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder={t("hero.searchPlaceholder", "Marque, modèle, type de véhicule…")}
                aria-label={t("hero.searchAria", "Rechercher un véhicule")}
                className="w-full h-12 sm:h-14 bg-white sm:bg-transparent border border-white/20 sm:border-0 rounded-full sm:rounded-none px-5 sm:pl-12 sm:pr-2 text-base font-sans focus-visible:ring-sky-400"
              />
            </div>
            <Button
              type="submit"
              size="lg"
              className="h-12 sm:h-12 rounded-full bg-sky-500 hover:bg-sky-600 text-white font-sans font-medium px-6 sm:px-8 gap-2 shadow-lg shadow-sky-500/30"
            >
              <Search aria-hidden="true" className="h-5 w-5 sm:hidden" />
              <span>{t("hero.searchButton", "Rechercher")}</span>
            </Button>
          </form>

          <nav
            aria-label={t("hero.secondaryNav", "Autres actions")}
            className="mt-6 flex flex-wrap items-center gap-x-1 gap-y-2 text-sm font-sans text-white/80"
          >
            <Link
              to="/recherche"
              className="hover:text-white transition-colors min-h-10 inline-flex items-center px-1"
            >
              {t("hero.linkBuy", "Acheter")}
            </Link>
            <span aria-hidden="true" className="text-white/40">·</span>
            <Link
              to="/location-longue-duree"
              className="hover:text-white transition-colors min-h-10 inline-flex items-center px-1"
            >
              {t("hero.linkRent", "Louer")}
            </Link>
            <span aria-hidden="true" className="text-white/40">·</span>
            <Link
              to="/estimation"
              className="hover:text-white transition-colors min-h-10 inline-flex items-center px-1"
            >
              {t("hero.linkEstimate", "Estimer ma voiture")}
            </Link>
          </nav>

          {stats && (stats.activeListings > 0 || stats.verifiedSellers > 0) ? (
            <p className="mt-12 text-xs sm:text-sm font-sans text-white/60 tracking-wide">
              {stats.activeListings > 0 ? (
                <span>
                  {t("hero.stats.activeListings", "{{count}} annonces actives", {
                    count: stats.activeListings,
                  })}
                </span>
              ) : null}
              {stats.activeListings > 0 && stats.verifiedSellers > 0 ? (
                <span aria-hidden="true" className="mx-2">·</span>
              ) : null}
              {stats.verifiedSellers > 0 ? (
                <span>
                  {t("hero.stats.verifiedSellers", "{{count}} vendeurs vérifiés", {
                    count: stats.verifiedSellers,
                  })}
                </span>
              ) : null}
            </p>
          ) : null}
        </div>
      </div>
    </section>
  );
}

export default HeroCinematic;
